name: Robot Applitools Tests
on:
  push:
    branches:
      - main
    schedule:
      - cron: 0 0 * * 5
    workflow_dispatch: null
jobs:
  setup:
    name: Setup the env and run the tests
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: latest

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements.txt

      - name: Run the tests
        run: |
          pabot --outputdir reports tests || true